/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutorSelectPanel.java
 *
 * Created on May 23, 2012, 1:21:34 PM
 */
package emt.tutor;

import emt.tutor.Tutor;
import java.util.ArrayList;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerModel;

/**
 *
 * @author David
 */
public class TutorSelectPanel extends javax.swing.JPanel {
    private ArrayList<Tutor> tutors;
    private int currentTutorIndex;
    
    /** Creates new form TutorSelectPanel */
    public TutorSelectPanel() {
        initComponents();
        tutors=new ArrayList<Tutor>();
        currentTutorIndex=-1;
    }
    
    public void addTutor(Tutor tutor) {
        if(!tutors.contains(tutor)) {
            tutors.add(tutor);
            TutorPanel newTutorPanel=new TutorPanel();
            newTutorPanel.setTutor(tutor);
            multiTutorPanel1.addTutor(tutor);
            
            if(currentTutorIndex==-1) {
                currentTutorIndex=0;
                updateTutor();
            }
        }
    }
    public void updateTutor() {
        tutorLabel.setText(tutors.get(currentTutorIndex).getName());
        multiTutorPanel1.switchTutor(tutors.get(currentTutorIndex).getName());
    }
    public void switchTutor(String tutorName) {
        for(Tutor tutor : tutors) {
            if(tutor.getName().equalsIgnoreCase(tutorName)) {
                currentTutorIndex=tutors.indexOf(tutor);
            }
        }
        updateTutor();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multiTutorPanel1 = new emt.tutor.MultiTutorPanel();
        previousTutorButton = new javax.swing.JButton();
        nextTutorButton = new javax.swing.JButton();
        tutorLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emt.EMTApp.class).getContext().getResourceMap(TutorSelectPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setMaximumSize(new java.awt.Dimension(148, 177));
        setMinimumSize(new java.awt.Dimension(148, 177));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(148, 177));

        multiTutorPanel1.setName("multiTutorPanel1"); // NOI18N

        previousTutorButton.setIcon(resourceMap.getIcon("previousTutorButton.icon")); // NOI18N
        previousTutorButton.setText(resourceMap.getString("previousTutorButton.text")); // NOI18N
        previousTutorButton.setName("previousTutorButton"); // NOI18N
        previousTutorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousTutorButtonActionPerformed(evt);
            }
        });

        nextTutorButton.setIcon(resourceMap.getIcon("nextTutorButton.icon")); // NOI18N
        nextTutorButton.setBorder(null);
        nextTutorButton.setName("nextTutorButton"); // NOI18N
        nextTutorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTutorButtonActionPerformed(evt);
            }
        });

        tutorLabel.setBackground(resourceMap.getColor("tutorLabel.background")); // NOI18N
        tutorLabel.setFont(resourceMap.getFont("tutorLabel.font")); // NOI18N
        tutorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tutorLabel.setText(resourceMap.getString("tutorLabel.text")); // NOI18N
        tutorLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tutorLabel.setName("tutorLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousTutorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tutorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextTutorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(multiTutorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tutorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(previousTutorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextTutorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(multiTutorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void previousTutorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousTutorButtonActionPerformed
        if(currentTutorIndex==0) {
            currentTutorIndex=tutors.size()-1;
        } else {
            currentTutorIndex--;
        }
        updateTutor();
    }//GEN-LAST:event_previousTutorButtonActionPerformed

    private void nextTutorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTutorButtonActionPerformed
        if(currentTutorIndex==tutors.size()-1) {
            currentTutorIndex=0;
        } else {
            currentTutorIndex++;
        }
        updateTutor();
    }//GEN-LAST:event_nextTutorButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private emt.tutor.MultiTutorPanel multiTutorPanel1;
    private javax.swing.JButton nextTutorButton;
    private javax.swing.JButton previousTutorButton;
    private javax.swing.JLabel tutorLabel;
    // End of variables declaration//GEN-END:variables
}
