/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutorContentPanel.java
 *
 * Created on May 28, 2012, 1:53:40 PM
 */
package emt.tutor;

import emt.tutor.actions.FeedbackPromptAction;
import emt.tutor.actions.TextFeedbackAction;
import java.awt.CardLayout;
import java.util.ArrayList;

/**
 *
 * @author David
 */
public class TutorContentPanel extends javax.swing.JPanel {
    private CardLayout myLayout;
    private TutorTextPanel myTextPanel;
    private TutorQuestionsPanel myQuestionsPanel;
    private TutorFeedbackPanel myFeedbackPanel;
    
    /** Creates new form TutorContentPanel */
    public TutorContentPanel() {
        initComponents();
        
        this.myLayout=new CardLayout();
        this.setLayout(myLayout);
        
        myTextPanel=new TutorTextPanel(this);
        myQuestionsPanel=new TutorQuestionsPanel(this);
        myFeedbackPanel=new TutorFeedbackPanel(this);
        
        this.add(myTextPanel, "Text");
        this.add(myQuestionsPanel, "Questions");
        this.add(myFeedbackPanel, "Prompt");
        
        ((CardLayout)this.getLayout()).show(this, "Text");
    }
    
    public void giveTextFeedback(TextFeedbackAction tfa) {
        myTextPanel.giveTextFeedback(tfa);
        myLayout.show(this, "Text");
    }
    public void giveQuestionList(ArrayList<QuestionItem> questions, String intro) {
        myQuestionsPanel.setIntro(intro);
        if(questions.size()>0) {
            myQuestionsPanel.setQuestion1(questions.get(0));
        } else {
            myQuestionsPanel.setQuestion1(new QuestionItem("",null));
        }
        if(questions.size()>1) {
            myQuestionsPanel.setQuestion2(questions.get(1));
        } else {
            myQuestionsPanel.setQuestion2(new QuestionItem("",null));
        }
        if(questions.size()>2) {
            myQuestionsPanel.setQuestion3(questions.get(2));
        } else {
            myQuestionsPanel.setQuestion3(new QuestionItem("",null));
        }
        if(questions.size()>3) {
            myQuestionsPanel.setQuestion4(questions.get(3));
        } else {
            myQuestionsPanel.setQuestion4(new QuestionItem("",null));
        }
        myLayout.show(this,"Questions");
    }
    public void giveFeedbackPrompt(FeedbackPromptAction prompt) {
        myFeedbackPanel.setPrompt(prompt);
        myLayout.show(this,"Prompt");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
