/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutorFeedbackPanel.java
 *
 * Created on May 28, 2012, 1:54:50 PM
 */
package emt.tutor;

/**
 *
 * @author David
 */
public class TutorFeedbackPanel extends javax.swing.JPanel {
    private TutorContentPanel myContentPanel;
    
    /** Creates new form TutorFeedbackPanel */
    public TutorFeedbackPanel(TutorContentPanel contentPanel) {
        initComponents();
        myContentPanel=contentPanel;
    }
    
    public void setPrompt(String prompt) {
        QuestionLabel.setText(prompt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FeedbackTextArea = new javax.swing.JTextArea();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emt.EMTApp.class).getContext().getResourceMap(TutorFeedbackPanel.class);
        QuestionLabel.setText(resourceMap.getString("QuestionLabel.text")); // NOI18N
        QuestionLabel.setName("QuestionLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        FeedbackTextArea.setColumns(20);
        FeedbackTextArea.setRows(5);
        FeedbackTextArea.setName("FeedbackTextArea"); // NOI18N
        jScrollPane1.setViewportView(FeedbackTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addComponent(QuestionLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea FeedbackTextArea;
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
