/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutorPopupFrame.java
 *
 * Created on May 24, 2012, 12:47:54 PM
 */
package emt.tutor;

import emt.tutor.actions.FeedbackPromptAction;
import emt.tutor.actions.TextFeedbackAction;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author David
 */
public class TutorPopupFrame extends javax.swing.JFrame {
    private TextFeedbackAction myTFA;
    
    /** Creates new form TutorPopupFrame */
    public TutorPopupFrame() {
        initComponents();
        this.setLocation(293,326);
    }
    
    public void switchImage(ImageIcon image) {
        tutorImageLabel.setIcon(image);
    }
    
    public void giveTextFeedback(String feedback) {
        tutorContentPanel1.giveTextFeedback(feedback);
    }
    public void giveTextFeedback(TextFeedbackAction tfa) {
        tutorContentPanel1.giveTextFeedback(tfa.getFeedback());
        myTFA=tfa;
    }
    public void giveQuestionList(ArrayList<QuestionItem> questions, String intro) {
        tutorContentPanel1.giveQuestionList(questions,intro);
    }
    public void giveFeedbackPrompt(FeedbackPromptAction prompt) {
        tutorContentPanel1.giveFeedbackPrompt(prompt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutorImageLabel = new javax.swing.JLabel();
        tutorContentPanel1 = new emt.tutor.TutorContentPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emt.EMTApp.class).getContext().getResourceMap(TutorPopupFrame.class);
        setTitle(resourceMap.getString("Tutor-Name.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("Tutor-Name"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        tutorImageLabel.setText(resourceMap.getString("tutorImageLabel.text")); // NOI18N
        tutorImageLabel.setName("tutorImageLabel"); // NOI18N

        tutorContentPanel1.setName("tutorContentPanel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tutorImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tutorContentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(tutorImageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tutorContentPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        if(!(myTFA==null)) {
            myTFA.setIsRead(true);
        }
    }//GEN-LAST:event_formComponentHidden

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private emt.tutor.TutorContentPanel tutorContentPanel1;
    private javax.swing.JLabel tutorImageLabel;
    // End of variables declaration//GEN-END:variables
}
