/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutorPopupFrame.java
 *
 * Created on May 24, 2012, 12:47:54 PM
 */
package emt.tutor;

import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author David
 */
public class TutorPopupFrame extends javax.swing.JFrame {

    /** Creates new form TutorPopupFrame */
    public TutorPopupFrame() {
        initComponents();
    }
    
    public void switchImage(ImageIcon image) {
        tutorImageLabel.setIcon(image);
    }
    
    public void giveTextFeedback(String feedback) {
        tutorContentPanel1.giveTextFeedback(feedback);
    }
    public void giveQuestionList(ArrayList<QuestionItem> questions) {
        tutorContentPanel1.giveQuestionList(questions);
    }
    public void giveFeedbackPrompt(String prompt) {
        tutorContentPanel1.giveFeedbackPrompt(prompt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutorImageLabel = new javax.swing.JLabel();
        tutorContentPanel1 = new emt.tutor.TutorContentPanel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emt.EMTApp.class).getContext().getResourceMap(TutorPopupFrame.class);
        tutorImageLabel.setText(resourceMap.getString("tutorImageLabel.text")); // NOI18N
        tutorImageLabel.setName("tutorImageLabel"); // NOI18N

        tutorContentPanel1.setName("tutorContentPanel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tutorImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tutorContentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(tutorImageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tutorContentPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private emt.tutor.TutorContentPanel tutorContentPanel1;
    private javax.swing.JLabel tutorImageLabel;
    // End of variables declaration//GEN-END:variables
}
