/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutorQuestionsPanel.java
 *
 * Created on May 28, 2012, 1:54:25 PM
 */
package emt.tutor.actionpanels;

import emt.tutor.QuestionItem;
import emt.tutor.StaticLogs;
import emt.tutor.TutorContentPanel;
import emt.tutor.actions.quiz.QuizChoiceAction;
import emt.tutor.actions.quiz.RepeatQuizAction;

/**
 *
 * @author David
 */
public class TutorQuizRepeatPanel extends javax.swing.JPanel {
    private TutorContentPanel myContentPanel;
    private RepeatQuizAction myRQA;
    
    public TutorQuizRepeatPanel(TutorContentPanel contentPanel) {
        initComponents();
        myContentPanel=contentPanel;
    }
    public void setRQA(RepeatQuizAction rqa) {
        myRQA=rqa;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        QuestionHeadingLabel = new javax.swing.JLabel();
        OptionBox1 = new javax.swing.JRadioButton();
        OptionBox2 = new javax.swing.JRadioButton();
        NextButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emt.EMTApp.class).getContext().getResourceMap(TutorQuizRepeatPanel.class);
        QuestionHeadingLabel.setFont(resourceMap.getFont("QuestionHeadingLabel.font")); // NOI18N
        QuestionHeadingLabel.setText(resourceMap.getString("QuestionHeadingLabel.text")); // NOI18N
        QuestionHeadingLabel.setName("QuestionHeadingLabel"); // NOI18N
        add(QuestionHeadingLabel);
        QuestionHeadingLabel.setBounds(10, 11, 530, 17);

        buttonGroup1.add(OptionBox1);
        OptionBox1.setText(resourceMap.getString("OptionBox1.text")); // NOI18N
        OptionBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OptionBox1.setName("OptionBox1"); // NOI18N
        add(OptionBox1);
        OptionBox1.setBounds(10, 32, 190, 14);

        buttonGroup1.add(OptionBox2);
        OptionBox2.setText(resourceMap.getString("OptionBox2.text")); // NOI18N
        OptionBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OptionBox2.setName("OptionBox2"); // NOI18N
        add(OptionBox2);
        OptionBox2.setBounds(10, 48, 230, 14);

        NextButton.setText(resourceMap.getString("NextButton.text")); // NOI18N
        NextButton.setName("NextButton"); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        add(NextButton);
        NextButton.setBounds(450, 120, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
    if(OptionBox1.isSelected()) {
        myRQA.repeatQuiz();
    } else {
        myRQA.endQuiz();
    }
}//GEN-LAST:event_NextButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JRadioButton OptionBox1;
    private javax.swing.JRadioButton OptionBox2;
    private javax.swing.JLabel QuestionHeadingLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
