/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutorQuestionsPanel.java
 *
 * Created on May 28, 2012, 1:54:25 PM
 */
package emt.tutor.actionpanels;

import emt.tutor.QuestionItem;
import emt.tutor.StaticLogs;
import emt.tutor.TutorContentPanel;
import emt.tutor.actions.quiz.QuizChoiceAction;

/**
 *
 * @author David
 */
public class TutorQuizCheckboxChoicePanel extends javax.swing.JPanel {
    private TutorContentPanel myContentPanel;
    private QuizChoiceAction myPrompt;
    
    public TutorQuizCheckboxChoicePanel(TutorContentPanel contentPanel) {
        initComponents();
        myContentPanel=contentPanel;
    }
    public void setQuizChoiceAction(QuizChoiceAction prompt) {
        myPrompt=prompt;
        setIntro(prompt.getPrompt());
        if(prompt.getOptions().size()>0) {
            setOption1(prompt.getOptions().get(0));
            OptionBox1.setVisible(true);
        } else {
            OptionBox1.setVisible(false);
        }
        if(prompt.getOptions().size()>1) {
            setOption2(prompt.getOptions().get(1));
            OptionBox2.setVisible(true);
        } else {
            OptionBox2.setVisible(false);
        }
        if(prompt.getOptions().size()>2) {
            setOption3(prompt.getOptions().get(2));
            OptionBox3.setVisible(true);
        } else {
            OptionBox3.setVisible(false);
        }
        if(prompt.getOptions().size()>3) {
            setOption4(prompt.getOptions().get(3));
            OptionBox4.setVisible(true);
        } else {
            OptionBox4.setVisible(false);
        }if(prompt.getOptions().size()>4) {
            setOption5(prompt.getOptions().get(4));
            OptionBox5.setVisible(true);
        } else {
            OptionBox5.setVisible(false);
        }
        if(prompt.getOptions().size()>5) {
            setOption6(prompt.getOptions().get(5));
            OptionBox6.setVisible(true);
        } else {
            OptionBox6.setVisible(false);
        }
    }
    public void setIntro(String intro) {
        QuestionHeadingLabel.setText(intro);
    }
    public void setOption1(String option) {
        OptionBox1.setText(option);
    }
    public void setOption2(String option) {
        OptionBox2.setText(option);
    }
    public void setOption3(String option) {
        OptionBox3.setText(option);
    }
    public void setOption4(String option) {
        OptionBox4.setText(option);
    }
    public void setOption5(String option) {
        OptionBox5.setText(option);
    }
    public void setOption6(String option) {
        OptionBox6.setText(option);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionHeadingLabel = new javax.swing.JLabel();
        OptionBox1 = new javax.swing.JCheckBox();
        OptionBox2 = new javax.swing.JCheckBox();
        OptionBox3 = new javax.swing.JCheckBox();
        OptionBox4 = new javax.swing.JCheckBox();
        NextButton = new javax.swing.JButton();
        OptionBox5 = new javax.swing.JCheckBox();
        OptionBox6 = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N
        setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emt.EMTApp.class).getContext().getResourceMap(TutorQuizCheckboxChoicePanel.class);
        QuestionHeadingLabel.setFont(resourceMap.getFont("QuestionHeadingLabel.font")); // NOI18N
        QuestionHeadingLabel.setText(resourceMap.getString("QuestionHeadingLabel.text")); // NOI18N
        QuestionHeadingLabel.setName("QuestionHeadingLabel"); // NOI18N
        add(QuestionHeadingLabel);
        QuestionHeadingLabel.setBounds(10, 11, 520, 17);

        OptionBox1.setText(resourceMap.getString("OptionBox1.text")); // NOI18N
        OptionBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OptionBox1.setName("OptionBox1"); // NOI18N
        add(OptionBox1);
        OptionBox1.setBounds(10, 32, 520, 14);

        OptionBox2.setText(resourceMap.getString("OptionBox2.text")); // NOI18N
        OptionBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OptionBox2.setName("OptionBox2"); // NOI18N
        add(OptionBox2);
        OptionBox2.setBounds(10, 48, 520, 14);

        OptionBox3.setText(resourceMap.getString("OptionBox3.text")); // NOI18N
        OptionBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OptionBox3.setName("OptionBox3"); // NOI18N
        add(OptionBox3);
        OptionBox3.setBounds(10, 65, 520, 14);

        OptionBox4.setText(resourceMap.getString("OptionBox4.text")); // NOI18N
        OptionBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OptionBox4.setName("OptionBox4"); // NOI18N
        add(OptionBox4);
        OptionBox4.setBounds(10, 81, 520, 14);

        NextButton.setText(resourceMap.getString("NextButton.text")); // NOI18N
        NextButton.setName("NextButton"); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        add(NextButton);
        NextButton.setBounds(450, 120, 80, 23);

        OptionBox5.setText(resourceMap.getString("OptionBox5.text")); // NOI18N
        OptionBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OptionBox5.setName("OptionBox5"); // NOI18N
        add(OptionBox5);
        OptionBox5.setBounds(10, 97, 520, 14);

        OptionBox6.setText(resourceMap.getString("OptionBox6.text")); // NOI18N
        OptionBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OptionBox6.setName("OptionBox6"); // NOI18N
        add(OptionBox6);
        OptionBox6.setBounds(10, 113, 520, 14);
    }// </editor-fold>//GEN-END:initComponents

private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
    myPrompt.next();
}//GEN-LAST:event_NextButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JCheckBox OptionBox1;
    private javax.swing.JCheckBox OptionBox2;
    private javax.swing.JCheckBox OptionBox3;
    private javax.swing.JCheckBox OptionBox4;
    private javax.swing.JCheckBox OptionBox5;
    private javax.swing.JCheckBox OptionBox6;
    private javax.swing.JLabel QuestionHeadingLabel;
    // End of variables declaration//GEN-END:variables
}
