/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutorQuestionsPanel.java
 *
 * Created on May 28, 2012, 1:54:25 PM
 */
package emt.tutor.actionpanels;

import emt.tutor.QuestionItem;
import emt.tutor.StaticLogs;
import emt.tutor.TutorContentPanel;

/**
 *
 * @author David
 */
public class TutorQuestionsPanel extends javax.swing.JPanel {
    private TutorContentPanel myContentPanel;
    private QuestionItem q1,q2,q3,q4;
    
    /** Creates new form TutorQuestionsPanel */
    public TutorQuestionsPanel(TutorContentPanel contentPanel) {
        initComponents();
        myContentPanel=contentPanel;
    }
    public void setIntro(String intro) {
        QuestionHeadingLabel.setText(intro);
    }
    public void setQuestion1(QuestionItem question) {
        q1=question;
        Question1Label.setText(question.getQuestion());
    }
    public void setQuestion2(QuestionItem question) {
        q2=question;
        Question2Label.setText(question.getQuestion());
    }
    public void setQuestion3(QuestionItem question) {
        q3=question;
        Question3Label.setText(question.getQuestion());
    }
    public void setQuestion4(QuestionItem question) {
        q4=question;
        Question4Label.setText(question.getQuestion());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question1Label = new javax.swing.JLabel();
        Question2Label = new javax.swing.JLabel();
        Question3Label = new javax.swing.JLabel();
        Question4Label = new javax.swing.JLabel();
        QuestionHeadingLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(emt.EMTApp.class).getContext().getResourceMap(TutorQuestionsPanel.class);
        Question1Label.setFont(resourceMap.getFont("QuestionHeadingLabel.font")); // NOI18N
        Question1Label.setForeground(resourceMap.getColor("Question3Label.foreground")); // NOI18N
        Question1Label.setText(resourceMap.getString("Question1Label.text")); // NOI18N
        Question1Label.setName("Question1Label"); // NOI18N
        Question1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Question1LabelMouseClicked(evt);
            }
        });

        Question2Label.setFont(resourceMap.getFont("QuestionHeadingLabel.font")); // NOI18N
        Question2Label.setForeground(resourceMap.getColor("Question3Label.foreground")); // NOI18N
        Question2Label.setText(resourceMap.getString("Question2Label.text")); // NOI18N
        Question2Label.setName("Question2Label"); // NOI18N
        Question2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Question2LabelMouseClicked(evt);
            }
        });

        Question3Label.setFont(resourceMap.getFont("QuestionHeadingLabel.font")); // NOI18N
        Question3Label.setForeground(resourceMap.getColor("Question3Label.foreground")); // NOI18N
        Question3Label.setText(resourceMap.getString("Question3Label.text")); // NOI18N
        Question3Label.setName("Question3Label"); // NOI18N
        Question3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Question3LabelMouseClicked(evt);
            }
        });

        Question4Label.setFont(resourceMap.getFont("QuestionHeadingLabel.font")); // NOI18N
        Question4Label.setForeground(resourceMap.getColor("Question3Label.foreground")); // NOI18N
        Question4Label.setText(resourceMap.getString("Question4Label.text")); // NOI18N
        Question4Label.setName("Question4Label"); // NOI18N
        Question4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Question4LabelMouseClicked(evt);
            }
        });

        QuestionHeadingLabel.setFont(resourceMap.getFont("QuestionHeadingLabel.font")); // NOI18N
        QuestionHeadingLabel.setText(resourceMap.getString("QuestionHeadingLabel.text")); // NOI18N
        QuestionHeadingLabel.setName("QuestionHeadingLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question1Label)
                            .addComponent(Question2Label)
                            .addComponent(Question3Label)
                            .addComponent(Question4Label)))
                    .addComponent(QuestionHeadingLabel))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionHeadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question4Label)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Question1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Question1LabelMouseClicked
        StaticLogs.Log("Tutor Question Clicked", myContentPanel.getTutorName(),q1.getQuestion());
        q1.getAction().doAction();
    }//GEN-LAST:event_Question1LabelMouseClicked

    private void Question2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Question2LabelMouseClicked
        StaticLogs.Log("Tutor Question Clicked", myContentPanel.getTutorName(),q2.getQuestion());
        q2.getAction().doAction();
    }//GEN-LAST:event_Question2LabelMouseClicked

    private void Question3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Question3LabelMouseClicked
        StaticLogs.Log("Tutor Question Clicked", myContentPanel.getTutorName(),q3.getQuestion());
        q3.getAction().doAction();
    }//GEN-LAST:event_Question3LabelMouseClicked

    private void Question4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Question4LabelMouseClicked
        StaticLogs.Log("Tutor Question Clicked", myContentPanel.getTutorName(),q4.getQuestion());
        q4.getAction().doAction();
    }//GEN-LAST:event_Question4LabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Question1Label;
    private javax.swing.JLabel Question2Label;
    private javax.swing.JLabel Question3Label;
    private javax.swing.JLabel Question4Label;
    private javax.swing.JLabel QuestionHeadingLabel;
    // End of variables declaration//GEN-END:variables
}
